DROP TABLE IF EXISTS todos CASCADE; 
DROP TABLE IF EXISTS users CASCADE; 
DROP TABLE IF EXISTS winners CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR UNIQUE NOT NULL 
);

CREATE TABLE todos (
  id VARCHAR PRIMARY KEY,
  owner VARCHAR REFERENCES users(username),
  text VARCHAR NOT NULL,
  completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE winners (
  id SERIAL PRIMARY KEY,
  username VARCHAR UNIQUE,
  ts TIMESTAMPTZ DEFAULT NOW()
);
